In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("customer.csv")
df.sample(5)

    age  gender   review education purchased
30   73    Male  Average        UG        No
26   53  Female     Poor        PG        No
25   57  Female     Good    School        No
42   30  Female     Good        PG       Yes
29   83  Female  Average        UG       Yes

In [3]:
df = df.iloc[:, 2:]

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df.drop("purchased", axis=1),
    df["purchased"],
    test_size=0.2,
)

In [5]:
from sklearn.preprocessing import OrdinalEncoder

X_train.head()

     review education
23     Good    School
7      Poor    School
27     Poor        PG
16     Poor        UG
29  Average        UG

In [6]:
oe = OrdinalEncoder(categories=[["Poor", "Average", "Good"], ["School", "UG", "PG"]])
oe.fit(X_train)
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [7]:
X_train

array([[2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [1., 2.],
       [2., 2.],
       [1., 0.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.]])

In [8]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
y_test = le.transform(y_test)